### ISSUE TITLE
Aggiornare l'elenco delle release

### ISSUE THREAD

**Issue by DrFredEdison** [zeroone2numeral2/tnt-village-bot#10]
TNT ha aperto per un breve periodo il mese scorso e ci sono state nuove release che non sono disponibili tramite il bot.

**Comment by zeroone2numeral2** [comment]
Ciao,

Il bot è stato aggiornato a fine marzo per aggiornare il proprio db con le nuove release di TNTVillage (vedi 7edda7a), quindi in teoria tutto ciò che è stato pubblicato dovrebbe essere nel db. A meno che non ci siano bug strani, tutto ciò che è stato postato in [@tntvillage_feeds](https://t.me/tntvillage_feeds) dovrebbe essere cercabile anche dal bot. Potresti farmi un esempio di torrent che manca?

**Comment by DrFredEdison** [comment]
Ciao!
TNT è stato riaperto per un brevissimo periodo tra fine aprile e inizio maggio, tempo che io e qualcun altro abbiamo sfruttato per fare la propria release trimestrale secondo il regolamento del release team.

Ti porto un esempio con una fatta ad me:

Titolo: Pippo nel pallone
Formato: Mkv
Data di release: 01/05/2020
Magnet:

magnet:?xt=urn:btih:199F88AB7C363EA21AA982004942C58F46092AD1&dn=Pippo_nel_pallone.mkv&tr=http%3a%2f%2ftracker.tntvillage.scambioetico.org%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.tntvillage.scambioetico.org%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2fIPv6.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.internetwarriors.net%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.tiny-vps.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.mg64.net%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce

Grazie per la disponibilità

**Comment by zeroone2numeral2** [comment]
Uhm, capisco. Premetto che sono completamente ignorante riguardo al funzionamento interno di TNTVillage e su chi/come pubblichi le release. Il bot in teoria dovrebbe aver salvato tutto ciò che è stato pubblicato nel [feed RSS](http://tntvillage.scambioetico.org/rss.php?c=0&p=10). Per caso queste release erano release che non venivano annunciate nella feed?

Comunque, se ne hai altri per favore girameli pure (bastano hash, titolo, data pubblicazione, nome di chi le ha pubblicate) qui o su Telegram (@throwawayusername)

**Comment by DrFredEdison** [comment]
Purtroppo non o se e come il feed RSS si aggiornava ancora, ma cercandola sul bot per curiosità mi sono accorto che la rel che ti indicavo prima mancava.
In questo momento il server si comporta come se avesse esaurito la banda, ma non escludo che sia stata volontariamente ridotta dai “piani alti” per limitarne l’accesso.

Grazie per il tuo lavoro ad ogni modo
Se dovessi avere novità di sorta ti scriverò
