### ISSUE TITLE
Inaccurate result

### ISSUE THREAD

**Issue by TheCrowned** [zeroone2numeral2/tnt-village-bot#2]
Hi there,
Mi sembra ci sia qualche problema con i risultati contenenti spazi. Se cerchi `Friends`, tra i risultati c'è anche la serie TV (per es. `Friends S06e19-20`). Tuttavia, se cerchi `Friends S06%` non vengono riportati risultati, e nemmeno con `Friends S%` o `Friends %` o `Friends_S%`. Credo di aver provato ogni combinazione :D

**Comment by zeroone2numeral2** [comment]
Ciao, scusa per la tarda risposta.

I risultati restituiti da una query di ricerca dipendono dalla [Full Text Search](https://sqlite.org/fts3.html) di SQLite, che non conosco molto bene - quindi dovrei dare un'occhiata a come funziona per capire come restituire dei risultati pertinenti anche in caso di ricerche come quella che hai portato come esempio

**Comment by cascafico** [comment]
> Hi there,
> Mi sembra ci sia qualche problema con i risultati contenenti spazi. Se cerchi `Friends`, tra i risultati c'è anche la serie TV (per es. `Friends S06e19-20`). Tuttavia, se cerchi `Friends S06%` non vengono riportati risultati, e nemmeno con `Friends S%` o `Friends %` o `Friends_S%`. Credo di aver provato ogni combinazione :D

Prova "Friends S01*", anche "^Friends S01*" da inizio riga.

**Comment by zeroone2numeral2** [comment]
Ho aggiornato il bot, ora dovrebbe restituire tutti i risultati anche senza utilizzare l'asterisco
