### ISSUE TITLE
pulsante copia

### ISSUE THREAD

**Issue by fiorins** [zeroone2numeral2/tnt-village-bot#3]
Consiglio l'aggiunta di un pulsante "copia" accanto a quello "comprimi" dopo che si clicca su "magnet con trackers" in modo da velocizzare la procedura

**Comment by zeroone2numeral2** [comment]
Un bot non può fare in modo che un testo venga copiato nella clipboard del tuo telefono/pc. Se stai usando Telegram Desktop, ti basta fare tasto destro -> copia per copiare il magnet coi trackers, mentre da Android/iOS ti basta semplicemente toccare il testo :)
